site_name: 100H-K8s
site_description: 100 小时后请叫我 K8s 管理员系列课程
site_author: ProjectTAM
site_url: https://100h-k8s.projecttam.com
copyright: Copyright © 2013 - 2022 ProjectTAM. All Rights Reserved.

repo_url: https://github.com/ProjectTAM/100H-K8s
repo_name: ProjectTAM/100H-K8s
edit_uri: ""

nav:
  - 目录: 
    - Index: index.md
    - Kubernetes 概述: Chapter01/chapter01.md
    - Kubernetes 架构: Chapter02/chapter02.md
    - Kubernetes 组件: Chapter03/chapter03.md
    - 使用 Minikube 搭建单节点集群: Chapter04/chapter04.md
    - Kubernetes 容器: Chapter05/chapter05.md
    - Kubernetes 工作负载: Chapter06/chapter06.md
    - Kubernetes 网络模型: Chapter07/chapter07.md
    - Kubernetes 服务: Chapter08/chapter08.md
    - Kubernetes 负载均衡: Chapter09/chapter09.md
    - Kubernetes 卷管理: Chapter10/chapter10.md
    - Kubernetes ConfigMap: Chapter11/chapter11.md
    - Kubernetes Secret: Chapter12/chapter12.md
    - Kubernetes 资源管理: Chapter13/chapter13.md
    - Kubernetes 调度: Chapter14/chapter14.md
    - Kubernetes 实践手册: Chapter15/chapter15.md
  - 关于:
    - 联系我们: about/contact.md
    - 许可协议: about/license.md
    - 更新日志: about/changelog.md
    - 参与创作: about/how-to-writing.md


theme:
  name: material
  custom_dir: overrides

  # 定义白天、黑夜阅读模式
  palette: 
    primary: white
    accent: green

  # 定义字体，text 为文本展示字体；code 为代码展示字体
  font:
    text: Noto Sans SC
    code: Azeret Mono
  
  # 定义站点语言，向左对齐
  language: zh
  direction: ltr

  # 定义站点图标
  icon:
    logo: material/bash
    repo: fontawesome/brands/github
  favicon: assets/images/favicon.png

  features:
    # 导航栏配置
    - navigation.instant
    - navigation.tracking
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - navigation.sections
    # - navigation.expand
    - navigation.indexes

    # 目录树配置
    - toc.follow
    # - toc.integrate

    # 搜索配置
    - search.suggest
    - search.highlight

    # 顶部公告已阅读状态
    - announce.dismiss

extra_javascript:
  - assets/javascripts/shortcuts.js
  - assets/stylesheets/extra.css

extra:
  # We love opensource
  # Please support this excellent project
  # https://github.com/sponsors/squidfunk
  # generator: false

  # 站点主页地址
  homepage: https://100h-k8s.projecttam.com
  
  # 社交主页
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/orgs/ProjectTAM
    - icon: fontawesome/solid/paper-plane
      link: mailto:admin@projecttam.com

plugins:
  - search:
      lang: en

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
